### PR TITLE
Fix file permissions for ExtensibleChannelMirror module

### PR DESCRIPTION
**Pull request by joseph-wakeling-sociomantic**
For some reason this source file was marked executable (!).

I've targeted this against the v13.3.x branch (i.e. current minor release series) since it's arguably a bugfix.  It can be rebased on an earlier branch if necessary.

### CODE REVIEW

**Review by nemanja-boric-sociomantic — APPROVED** [review]

**Comment by joseph-wakeling-sociomantic** [comment]
@nemanja-boric-sociomantic are you happy with the targeted branch?

**Comment by nemanja-boric-sociomantic** [comment]
Yes, I'm happy with the targeted branch. It will be merged from here and fixed in all maintained branches.

**Comment by gavin-norman-sociomantic** [comment]
Puh... I wouldn't really count this as a bug fix.

**Comment by nemanja-boric-sociomantic** [comment]
The I suggest we only apply it to v13.x.x and it will eventually go into v14.x.x.

**Comment by joseph-wakeling-sociomantic** [comment]
OK, shall I rebase and re-target?

**Comment by gavin-norman-sociomantic** [comment]
Yeah, it's not worth making a patch release for this.

**Comment by nemanja-boric-sociomantic** [comment]
I've adjusted the milestone accordingly. Please retarget first and then rebase, so the travis gets triggered with the right target branch.

**Comment by joseph-wakeling-sociomantic** [comment]
Already retargeted, rebase coming up ;-)

**Comment by joseph-wakeling-sociomantic** [comment]
Rebased on `v13.x.x`.

**Comment by nemanja-boric-sociomantic** [comment]
Thanks!

**Pull request merged**
