### PR TITLE
Adapt Get, Put, GetChannels to use new SupportedCode from swarm

### PR DESCRIPTION
**Pull request by gavin-norman-sociomantic**

### CODE REVIEW

**Comment by gavin-norman-sociomantic** [comment]
Gah, it's too early in the year for flaky tests :(

**Comment by gavin-norman-sociomantic** [comment]
Interesting... it seems that reading and checking the started / error code in the `handleSupportedCode` method (instead of in the `handle` method) fixes the flaky tests. I'm not entirely sure why.

**Comment by gavin-norman-sociomantic** [comment]
Green now.

>Interesting... it seems that reading and checking the started / error code in the handleSupportedCode method (instead of in the handle method) fixes the flaky tests. I'm not entirely sure why.

@nemanja-boric-sociomantic interested whether you have any thoughts on that. The most obvious thing I can think of is what will happen in [`AllNodesRequest.run`](https://github.com/sociomantic-tsunami/swarm/blob/v4.x.x/src/swarm/neo/client/mixins/AllNodesRequestCore.d#L127-L164). I don't see what difference that would make, though.

**Comment by nemanja-boric-sociomantic** [comment]
I'm sceptical towards the fact that this caused/fixed flaky tests :thinking: .

**Comment by gavin-norman-sociomantic** [comment]
Ditto.

**Comment by gavin-norman-sociomantic** [comment]
It was very repeatable, though. With the previous change: ~2/4 builds would fail. With the current change: no builds fail.

**Comment by gavin-norman-sociomantic** [comment]
How ironic that as soon as I type that, I notice that the current build has failed with the same problem :D

**Comment by gavin-norman-sociomantic** [comment]
Moved flaky part to https://github.com/sociomantic-tsunami/dhtproto/pull/93.

**Comment by nemanja-boric-sociomantic** [comment]
:+1: Looks very noncontroversal.

**Pull request merged**
