### PR TITLE
Modify legacy RemoveChannel behaviour to not remove listened channels

### PR DESCRIPTION
**Pull request by gavin-norman-sociomantic**

### CODE REVIEW

**Comment by gavin-norman-sociomantic** [comment]
Thinking about release notes for this:
* It's not a breaking change to the API.
* It's also not a breaking change to the protocol.
* It _is_, however, a change to the request's behaviour.

We don't really have a release notes section for such changes, at present. Maybe we could add a new category for the *proto repos? (Though that would probably require support in `neptune-release`.) Or we just count it as a migration instruction? Any other ideas?

**Comment by nemanja-boric-sociomantic** [comment]
I would keep it simple and count this as a migration instructions, as I'm inclined to look into this as a _behavioral_ breaking change, as the legitimate use cases that used to work now doesn't work anymore (for example, there are legitimate cases where we are resetting channels in the DHT by removing the channel, which will not work anymore, unless all listeners are down, we're not just using RemoveChannel to remove the orphan channels).

**Comment by gavin-norman-sociomantic** [comment]
>there are legitimate cases where we are resetting channels in the DHT by removing the channel

Ah, interesting. I'd forgotten about those. Essentially using `RemoveChannel` as a "delete all records". Ah well, such uses are obscure.

**Comment by gavin-norman-sociomantic** [comment]
Updated to the Nemanja solution: each test case operates on its own channel.

**Comment by gavin-norman-sociomantic** [comment]
Updated with release notes.

**Comment by gavin-norman-sociomantic** [comment]
This change is getting too complicated:
* As seen in this PR, changing the behaviour of RemoveChannel affects the legacy tests.
* Switching all test cases (in the neo branch) to use the neo RemoveChannel doesn't work, because of the different behaviour of Listen.
* We could implement a unix socket command to clear the state of the DHT after a test case, but then we wouldn't want to deploy this to live DHTs!

The impetus for this change was to simplify the Mirror request (see #39). While this would be a nice thing to do, it's far from urgent. Mirror works as it is, it just has a slight and obscure complication in its usage (user code must handle what to do if the mirrored channel is removed). Given the complications above, it's not worth making this change now. We can wait until the legacy requests are no longer in use, then make a new version of Mirror and RemoveChannel with this altered behaviour.

**Pull request closed without merging**
