### PR TITLE
Adapt Mirror to use new SupportedCode from swarm

### PR DESCRIPTION
**Pull request by gavin-norman-sociomantic**
Part of #78.

### CODE REVIEW

**Comment by nemanja-boric-sociomantic** [comment]
This just got retested, let's see how flaky you are.

**Comment by gavin-norman-sociomantic** [comment]
>Interesting... it seems that reading and checking the started / error code in the `handleSupportedCode` method (instead of in the `handle` method) fixes the flaky tests. I'm not entirely sure why.

Making this change seems to trigger flakiness in the Mirror tests. It's not clear, however, whether they were already flaky, and this change just ups the chances.

**Comment by gavin-norman-sociomantic** [comment]
>This just got retested, let's see how flaky you are.

Flaky!

**Comment by gavin-norman-sociomantic** [comment]
>It's not clear, however, whether they were already flaky, and this change just ups the chances.

Seems it's actually unrelated. We just had a failure in a build without this change: https://travis-ci.org/sociomantic-tsunami/dhtproto/jobs/327184612#L774

**Comment by gavin-norman-sociomantic** [comment]
Replaced by #94.

**Pull request closed without merging**
