### PR TITLE
Reject big records

### PR DESCRIPTION
**Pull request by gavin-norman-sociomantic**
Based on #42. (Blocked.)

### CODE REVIEW

**Comment by david-eckardt-sociomantic** [comment]
What would happen currently, without checking the record size and responding with `ValueTooBig`, if a batch request comes across a too big record? Would the batch request just fail with `Error`?

**Comment by david-eckardt-sociomantic** [comment]
Can you even add a record with the length of `RecordBatcher.DefaultMaxBatchSize` to a batch? I mean, first the `size_t` length of the record will be added to the batch, then the record data, so the batch length should be `size_t.sizeof + DefaultMaxBatchSize` then -- perhaps `DefaultMaxBatchSize - size_t.sizeof` is the actual record size limit?

**Comment by gavin-norman-sociomantic** [comment]
>What would happen currently, without checking the record size and responding with ValueTooBig, if a batch request comes across a too big record? Would the batch request just fail with Error?

Currently, the GetAll request just skips the too big record, logs a warning, and continues with the iteration: https://github.com/sociomantic-tsunami/dhtproto/blob/neo/src/dhtproto/node/neo/request/GetAll.d#L314-L319

**Comment by gavin-norman-sociomantic** [comment]
>Can you even add a record with the length of RecordBatcher.DefaultMaxBatchSize to a batch? I mean, first the size_t length of the record will be added to the batch, then the record data, so the batch length should be size_t.sizeof + DefaultMaxBatchSize then -- perhaps DefaultMaxBatchSize - size_t.sizeof is the actual record size limit?

Good point. I think you're probably right. I'l investigate this and add a test with GetAll to ensure that a record with the maximum allowed value size can indeed be successfully returned to the client via GetAll.

(I believe the legacy protocol has the same problem, btw.)

**Comment by gavin-norman-sociomantic** [comment]
Actually, the best way to phrase this would be for the DHT's batch size to be set in terms of `MaxRecordSize + size_t.sizeof`. The batch size is an internal detail of the GetAll request, so it doesn't make sense to require the Put request to know about this.

**Comment by gavin-norman-sociomantic** [comment]
Updated:
* One record of max size, including key, will fit in a GetAll batch.
* Add a test that a record of max size can be returned by GetAll.

**Comment by gavin-norman-sociomantic** [comment]
#42 merged. Unblocked.

**Review by david-eckardt-sociomantic — APPROVED** [review]

**Pull request merged**
