### PR TITLE
Fix compilation with dmd 2.071

### PR DESCRIPTION
**Pull request by gavin-norman-sociomantic**

### CODE REVIEW

**Comment by nemanja-boric-sociomantic** [comment]
Not in the v13.3.x?

**Comment by gavin-norman-sociomantic** [comment]
Oh true :man_facepalming:

**Comment by gavin-norman-sociomantic** [comment]
Rebased.

**Review by nemanja-boric-sociomantic — APPROVED** [review]

**Comment by gavin-norman-sociomantic** [comment]
>./submodules/turtle/src/turtle/runner/Runner.d(268): Error: no property 'listAllTests' for type 'Actions', did you mean 'listAllTests'?

Hmmm...

**Comment by gavin-norman-sociomantic** [comment]
test this please travis

**Pull request merged**
