### PR TITLE
Update ocean, swarm and turtle to latest HEAD and test with newest compilers

### PR DESCRIPTION
**Pull request by mathias-lang-sociomantic**
```
* submodules/ocean v3.3.1(a991c41)...v3.5.5+61(f491c8f) (187 commits)
  > Always resolve getMsg(e) to e.message()
  > Start testing with upstream 2.077 DMD
  > Fix implicit string concatenation
  > D2 compatible null handling in old Layout
  > Remove left-over convert dependency
  (...)

* submodules/swarm v4.2.1(384794b)...v4.4.0+10(28126d5) (70 commits)
  > Test with upstream v2.077.*
  > Remove support for client per-RoC working data
  > Update to ocean v4.x.x HEAD
  > Use most recent supported compiler versions
  > Support dmd-transitional 2.071.2.s2
  (...)

* submodules/turtle v8.0.0(a319c42)...v8.2.1+4(a79585d) (19 commits)
  > Remove unused import
  > Basic CircleCI test script
  > Remove travis.yml
  > Merge tag v8.2.1 into v8.x.x
  > Collect peak virtual memory usage of the app
  (...)
```

### CODE REVIEW

**Comment by gavin-norman-sociomantic** [comment]
This PR makes D2 unhappy :(

**Comment by mathias-lang-sociomantic** [comment]
Trust me, it makes me unhappy as well. Depends on https://github.com/sociomantic-tsunami/swarm/pull/180

**Comment by mathias-lang-sociomantic** [comment]
Fixed :tada:

**Comment by mathias-lang-sociomantic** [comment]
Ping :angel:

**Review by gavin-norman-sociomantic — APPROVED** [review]

**Pull request merged**
