### PR TITLE
Update to swarm v4.5.0

### PR DESCRIPTION
**Pull request by gavin-norman-sociomantic**
Includes merging master into neo.

### CODE REVIEW

**Comment by nemanja-boric-sociomantic** [comment]
The commit message of the merge commit indicates merging into this branch, but it should say `into neo branch`.

**Comment by gavin-norman-sociomantic** [comment]
Ah yes. Updated.

**Review by nemanja-boric-sociomantic — APPROVED** [review]

**Comment by nemanja-boric-sociomantic** [comment]
I assume you just want to push this, not to rebase?

**Comment by nemanja-boric-sociomantic** [comment]
:+1:

**Pull request merged**
